sudo: required
services:
    - docker

before_install:
    - docker build -t loschtreality/docker-react -f Dockerfile.dev .

script:
    - docker run loschtreality/docker-react npm run test -- --coverage