sudo: required
services:
    - docker

before_install:
    - docker build -t loschtreality/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true loschtreality/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "DockerReact"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-658218766919"
    bucket_path: "DockerReact"
    on:
        branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

language: generic